name: places_resnet50_arbloss_ugcc_mixup
print_freq: 100
workers: 48
log_dir: 'logs'
model_dir: 'ckps'


arbloss: True
arb_loss_use_global_class_cnt: True


# dataset & model setting
dataset: 'places'
data_path: './data/Places/Places-LT'
num_classes: 365
imb_factor: null
backbone: 'resnet50_fe'
resume: ''
head_class_idx:
  - 0
  - 131
med_class_idx:
  - 131
  - 288
tail_class_idx:
  - 288
  - 365


# distributed training
deterministic: False
distributed: True
gpu: null
world_size: 8
rank: -1
dist_url: 'env://'
dist_backend: 'nccl'
multiprocessing_distributed: False


# Train
mode: 'stage1'
lr: 0.1
batch_size: 1024
weight_decay: 5e-4
num_epochs: 90
momentum: 0.9
cos: True
mixup: True
alpha: 0.2




